# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
# 
# Liquid docs: https://shopify.github.io/liquid/
# Jekyll docs: https://jekyllrb.com/docs/

title: Adam Blighe
author: Adam Blighe
email: blog.exporter575@slmails.com
description: >-
  Hey! This place has random writing about stuff I'm doing or interested in,
  and also serves as a portfolio of sorts. Thanks for checking it out!

baseurl: ""
url: "https://nospawnn.github.io"

permalink: /:year/:month/:day/:title:output_ext

# Social links
github_username:  nospawnn
linkedin_username: adam-blighe
mastodon:
  - username: nospawnn
    instance: mastodon.social

# Build settings
theme: minima
minima:
  date_format: "%B %e, %Y"

show_excerpts: true

timezone: Europe/London

plugins:
  - jekyll-feed

include:
  - _pages

header_pages:
  - _pages/about.md
  - _pages/blog.md
  - _pages/topics.md

defaults:
  - scope:
      path: _pages
    values:
      layout: page

collections_dir: collections
collections:
  aoc:
    output: true
    relative_directory: topics/aoc

kramdown:
  highlighter: rouge
  syntax_highlighter_opts:
      block:
          line_numbers: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
